language: go
# go modules require xenial for mercurial TLS 1.2 support
dist: xenial

go:
- 1.12.7
- 1.x
env:
- GO111MODULE=on
cache:
  directories:
  - vendor/
install:
- make install-tools
- make vendor
script:
- make validate
- make test
