apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-dns-exposer
spec:
  replicas: 1
  selector:
    matchLabels:
      name: k8s-dns-exposer
  template:
    metadata:
      labels:
        name: k8s-dns-exposer
    spec:
      serviceAccountName: k8s-dns-exposer
      containers:
        - name: k8s-dns-exposer
          image: datadog/k8s-dns-exposer-controller:v0.0.1
          #command:
          #- k8s-dns-exposer
          imagePullPolicy: Always
          args:
            - --zap-devel 
            - --zap-level=debug
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "k8s-dns-exposer"
