kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-dns-exposer
subjects:
- kind: ServiceAccount
  name: k8s-dns-exposer
roleRef:
  kind: Role
  name: k8s-dns-exposer
  apiGroup: rbac.authorization.k8s.io
